language: node_js
node_js:
 - "12"
services:
 - docker
jobs:
  include:
    - stage: Tests
      name: Unit Test JS
      script:
      - npm install
      - npm test
    - stage: Build Docker Image
      name: Build Images Docker
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t test_node_js_deploy .
      - docker images
      - docker tag test_node_js_deploy $DOCKER_USERNAME/test_node_js_deploy
      - docker push $DOCKER_USERNAME/test_node_js_deploy